# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://macols.github.io
title: Service Fabric 
email: t-maols@microsoft.com
author: MacKenzie Olson
description: > # "Write an awesome description for your new site here. 
  Centralized source for all resources (from Service Fabric developers and users alike) in one convenient location.
copyright: 'Copyright &copy; 2018 Microsoft. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Microsoft/service-fabric
  - title: linkedin
    url: https://www.linkedin.com/groups/8526708/profile
  - title: stack overflow
    url: https://stackoverflow.com/questions/tagged/azure-service-fabric
  - title: calendar
    url: https://bing.com